name: Pre-release Build
on: workflow_dispatch

permissions:
  contents: write

concurrency:
  group: pre-release
  cancel-in-progress: true

jobs:
  Build-Linux:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        run: |
          curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=stable --profile=minimal
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Build
        run: |
          cargo build

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Pre-release
          prerelease: true
          overwrite_files: true
          files: target/debug/diffcsv
          tag_name: pre-release-marker

  Build-Windows:
    runs-on: windows-2025
    needs: Build-Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          cargo build --verbose

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Pre-release
          prerelease: true
          overwrite_files: true
          files: |
            target/debug/diffcsv.exe
            target/debug/diffcsv.pdb
          tag_name: pre-release-marker

